### ISSUE TITLE
Intégrer Webmecanik/mautic dans tarteaucitron.js (5)

### ISSUE THREAD

**Issue by npracht** [Webmecanik/tarteaucitron.js#1]
# Besoin
Proposer à mes visiteurs de désactiver le script de tracking à travers un form/bouton

- [x] Intégration Webmecanik au script
- [x] Documentation utilisateur pour une agence

**Comment by MaxWebmecanik** [comment]
@npracht Tu me confirme que je nomme tout Automation et que la config se fait par l'URL entier et pas par seulement le **prefix**.auto.wmk.com

**Comment by npracht** [comment]
prefix

--
*Norman Pracht*
Chief Marketing Officer
Webmecanik
+33 6 49 46 70 68
Discover how Renault Sport
<http://www.webmecanik.com/fr/automation/resources/whitebooks/success-story-…>
has
increased it's email open rate by 75% thanks to Marketing Automation!
Webmecanik Demo
<https://www.youtube.com/watch?v=PbeyJBDeXR8&feature=youtu.be> - How to
deploy Webmecanik Automation in a few clicks
<https://www.youtube.com/watch?v=e22q644HzPI>


2017-02-13 10:17 GMT+01:00 Maximilien Mellen <notifications@github.com>:
